language: java
script: mvn package -Pvzwallet
 deploy:
   edge: true
   provider: cloudfoundry
   username: vzwallet@gmail.com
   password: Verizon!1
   api: https://api.run.pivotal.io
   organization: vzwallet
   space: staging
   deployment_branch: "vzwallet-patch-1"
