language: java
script: mvn package -Pvzwallet
deploy:
  edge: true
  provider: cloudfoundry
  #user: "vzwallet@gmail.com"
  username: "vzwallet@gmail.com"
  password: "Verizon!1" 
  api: "https://api.run.pivotal.io"
  #domain: "cfapps.io"
  app: "vzwallet"
  appname: "vzwallet"
  organization: vzwallet
  space: "staging"
  skip_cleanup: true

