language: java
script: mvn package -Pvzwallet
deploy:
  provider: cloudfoundry
  user: "vzwallet@gmail.com"
  password: "Verizon!1"  # can be encrypted
  domain: "krishs"
  app: "vzwallet"
  skip_cleanup: true
  #deployment_branch: "vztest"
