language: java
script: mvn package -Pvzwallet
deploy:
  provider: cloudfoundry
  user: "vzwallet@gmail.com"
  username: "vzwallet@gmail.com"
  password: "Verizon!1" 
  api: "https://api.run.pivotal.io"
  domain: "krishs"
  app: "vzwallet"
  space: "staging"
  organization: vzwallet
  skip_cleanup: true
