language: java
script: mvn package -Pvzwallet
deploy:
  provider: cloudfoundry
  user: "vzwallet@gmail.com"
  username: "vzwallet@gmail.com"
  password: "Verizon!1" 
  api: "https://api.run.pivotal.io"
  domain: "vzwallet.com"
  app: "vzwallet"
  organization: vzwallet
  space: "development"
  skip_cleanup: true
